### ISSUE TITLE
updated advancement sheet 

### ISSUE THREAD

**Issue by palmaguire** [jlessard93/uriptfu#4]
Please replace the Level Advancement with this new version. TY

[Advancement Form with Info 2017.pdf](https://github.com/jlessard93/uriptfu/files/1768884/Advancement.Form.with.Info.2017.pdf)

**Comment by jlessard93** [comment]
closing because of #5

**Comment by palmaguire** [comment]
I was going to do that but wasn't sure how.



Sincerely,
Patricia Maguire
PTFU/Executive Director

Rodman Hall Rm 119
94 W Alumni Ave
University of Rhode Island
Kingston, Rhode Island 02881

(401) 874-4481
uriptfu.org
