### ISSUE TITLE
Scratch the last Advancement form and use this one to replace

### ISSUE THREAD

**Issue by palmaguire** [jlessard93/uriptfu#5]
Scratch the last Advancement form and use this one to replace.
Sorry, I looked at it and when I scanned the papers they just looked awful after I open it. These look much better.  Thank you, thank you.

[Salary Advancement Info 2017 .pdf](https://github.com/jlessard93/uriptfu/files/1768944/Salary.Advancement.Info.2017.pdf)

**Comment by palmaguire** [comment]
Hi,

Please remove the Fax number and the little icon. I got rid of the fax machine. Thanks  :)

**Comment by jlessard93** [comment]
this is replacing #4

**Comment by jlessard93** [comment]
#9 has these changes
